### ISSUE TITLE
LSPDFR crash wasn't detected

### ISSUE THREAD

**Issue by Michael21107** [SuperPyroManiac/LSPDFR-Helper#1]
```
[11/29/2024 1:59:24 AM.598] LSPD First Response: 
[11/29/2024 1:59:24 AM.598] LSPD First Response: ==============================
[11/29/2024 1:59:24 AM.598] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[11/29/2024 1:59:24 AM.598] LSPD First Response: ------------------------------
[11/29/2024 1:59:24 AM.598] LSPD First Response: Origin: Game fiber "MenuManager".
[11/29/2024 1:59:24 AM.598] LSPD First Response: ------------------------------
[11/29/2024 1:59:24 AM.598] LSPD First Response: Exception type: System.NullReferenceException
[11/29/2024 1:59:24 AM.598] LSPD First Response: Exception message: Object reference not set to an instance of an object.
[11/29/2024 1:59:24 AM.598] LSPD First Response: ------------------------------
[11/29/2024 1:59:24 AM.598] LSPD First Response: Inner exceptions:
[11/29/2024 1:59:24 AM.598] LSPD First Response: ------------------------------
[11/29/2024 1:59:24 AM.598] LSPD First Response: Stack trace:
[11/29/2024 1:59:24 AM.598] LSPD First Response: at ESUyHnNPEkDcfLEZOUxuKYNATBao.IjzfCzEShufQzbEGIRLjRwFOiHMdb() in D:\GTA V\LSPD First Response\LSPD First Response\Mod\MenuManager.cs:line 191
[11/29/2024 1:59:24 AM.598] at ESUyHnNPEkDcfLEZOUxuKYNATBao.TrWGGxGeqZDveTteddXAUmMZSzky() in D:\GTA V\LSPD First Response\LSPD First Response\Mod\MenuManager.cs:line 235
[11/29/2024 1:59:24 AM.598] at sihzRVdkOGfCovEYLdtbCMnpbQlv.sGWOzlXfqUrackafxsjvPqLpLxCq() in D:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\ThreadedScriptComponent.cs:line 65
[11/29/2024 1:59:24 AM.598] at Rage.GameFiber.Main()
[11/29/2024 1:59:24 AM.598] LSPD First Response: ==============================
[11/29/2024 1:59:24 AM.598] LSPD First Response: 
[11/29/2024 1:59:24 AM.601] LSPD First Response: [FATAL] Forced termination
[11/29/2024 1:59:24 AM.604] LSPD First Response: [TRACE] Released 0 entities from DefaultContentManager
[11/29/2024 1:59:27 AM.872] LSPD First Response: [INFO] LSPDFR has shut down
[11/29/2024 1:59:27 AM.873] LSPD First Response: GameFiber::Main() - Critical error on fiber shutdown: TLS no longer matches initial TLS
[11/29/2024 1:59:28 AM.188] LSPD First Response: GameFiber::Main() - Critical error on fiber shutdown: TLS no longer matches initial TLS
``` 
[RagePluginHook.log](https://github.com/user-attachments/files/17970839/RagePluginHook.log)

**Comment by SuperPyroManiac** [comment]
Im not sure what the crash was caused by, for now im going to skip over this.
